export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const GET_USER = "GET_USER";
export const GET_AVAILABLE_USERS = "GET_AVAILABLE_USERS";
export const GET_NOTIFICATIONS = "GET_NOTIFICATIONS";
export const GET_ADMIN_NOTIFICATIONS = "GET_ADMIN_NOTIFICATIONS";
export const GET_USER_POINTS = "GET_USER_POINTS";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";